name: 03 - Python Script Workflow

env:
  DEVOPS_DIR: prettymapsbot

on:
  schedule:
  - cron: "20 11 * * *"    #runs at 6:30 UTC everyday
  workflow_dispatch:

jobs:

  build:
    name: prettymapsbot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Install the python version needed

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests

      - name: Execute Python script # Run the run.py to get the latest data
        run: python ${{ env.DEVOPS_DIR }}/pretty-maps.py
        shell: sh
